### ISSUE TITLE
Review font size setting for whole document

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/recursos-digitales#4]
The following `\large` macro makes everything that comes next appear larger:

https://github.com/asrob-uc3m/recursos-digitales/blob/0b9612cdccd4f30aa948aff76b1efacc378b89f9/plantillas/grado/evaluacion.tex#L21-L22

Since `evaluacion.tex` is near the top of the transclusion list at `TFG.tex`, the font size for the whole document is altered by that single command.

I propose:

1. if this was not intended, enclose `\large` in its own scope, e.g. `{\large blahblahblah}`, or
2. if this is the desired font size, proceed as in 1. and apply such configuration in a visible place at `TFG.tex` instead.

**Comment by jgvictores** [comment]
I'd suppose this was not intended, and go for 1.
